Repository reoxidant/practice-swift, pull requests merged in 2022-01, with the labels that each got.

#458 created the ProductListMVVM project
  Projects/ProductListMVVM/ProductListMVVM.xcodeproj/project.pbxproj
  Projects/ProductListMVVM/ProductListMVVM/DetailProductModule/DetailProductViewController.swift
  Projects/ProductListMVVM/ProductListMVVM/DetailProductModule/DetailProductViewModel.swift
  Projects/ProductListMVVM/ProductListMVVM/Models/Product.swift
  Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductCellModule/ProductCellViewModel.swift
  Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductCellModule/ProductTableViewCell.swift
  Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductListTableViewController.swift
  Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductListViewModel.swift
  Projects/ProductListMVVM/ProductListMVVM/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/ProductListMVVM/ProductListMVVM/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/ProductListMVVM/ProductListMVVM/Resources/Assets.xcassets/Contents.json
  Projects/ProductListMVVM/ProductListMVVM/Services/DataManager.swift
  Projects/ProductListMVVM/ProductListMVVM/Services/NetworkManager.swift
  Projects/ProductListMVVM/ProductListMVVM/Storyboards/Base.lproj/LaunchScreen.storyboard
  Projects/ProductListMVVM/ProductListMVVM/Storyboards/Base.lproj/Main.storyboard
  Projects/ProductListMVVM/ProductListMVVM/Supporting Files/AppDelegate.swift
  Projects/ProductListMVVM/ProductListMVVM/Supporting Files/Info.plist
  Projects/ProductListMVVM/ProductListMVVM/Supporting Files/SceneDelegate.swift
Labels: enhancement

#459 practiced with the operation queue and added the box binding method to ProductListMVVM project
  Playgrounds/Concurrency/OperationQueue.playground/Pages/Operation.xcplaygroundpage/Contents.swift
  Playgrounds/Concurrency/OperationQueue.playground/Pages/Operation.xcplaygroundpage/timeline.xctimeline
  Playgrounds/Concurrency/OperationQueue.playground/Pages/OperationQueue.xcplaygroundpage/Contents.swift
  Playgrounds/Concurrency/OperationQueue.playground/Resources/dark_road_small.jpg
  Playgrounds/Concurrency/OperationQueue.playground/Sources/Duration.swift
  Playgrounds/Concurrency/OperationQueue.playground/contents.xcplayground
  Playgrounds/Concurrency/OperationQueue.playground/playground.xcworkspace/contents.xcworkspacedata
  Projects/ProductListMVVM/ProductListMVVM.xcodeproj/project.pbxproj
  Projects/ProductListMVVM/ProductListMVVM/DetailProductModule/DetailProductViewController.swift
  Projects/ProductListMVVM/ProductListMVVM/DetailProductModule/DetailProductViewModel.swift
  Projects/ProductListMVVM/ProductListMVVM/Helpers/Box.swift
  Projects/ProductListMVVM/ProductListMVVM/Services/NetworkManager.swift
Labels: enhancement

#460 initialized root window and added the NewContactModule in the ContactListMVP
  Projects/ContactListMVP/ContactListMVP/NewContactModule/Presenter/NewContactPresenter.swift
  Projects/ContactListMVP/ContactListMVP/NewContactModule/Views/NewContactViewController.swift
  Projects/ContactListMVP/ContactListMVP/NewContactModule/Views/NewContactViewController.xib
  Projects/ContactListMVP/ContactListMVP/SupportingFiles/SceneDelegate.swift
Labels: enhancement

#461 created the unit tests an UI tests in ContactListMVP project
  Projects/ContactListMVP/ContactListMVP.xcodeproj/project.pbxproj
  Projects/ContactListMVP/ContactListMVPTests/ContactListPresenterTests.swift
  Projects/ContactListMVP/ContactListMVPTests/RouterTests.swift
  Projects/ContactListMVP/ContactListMVPUITests/ContactListMVPUITests.swift
  Projects/ContactListMVP/ContactListMVPUITests/ContactListMVPUITestsLaunchTests.swift
Labels: enhancement

#462 initialized the ProductListSwiftUI project and added Product model
  Projects/ProductListSwiftUI/ProductListSwiftUI.xcodeproj/project.pbxproj
  Projects/ProductListSwiftUI/ProductListSwiftUI/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/ProductListSwiftUI/ProductListSwiftUI/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/ProductListSwiftUI/ProductListSwiftUI/Assets.xcassets/Contents.json
  Projects/ProductListSwiftUI/ProductListSwiftUI/Models/Product.swift
  Projects/ProductListSwiftUI/ProductListSwiftUI/Preview Content/Preview Assets.xcassets/Contents.json
Labels: enhancement

#463 refactor(HowOldAmI): renamed path to info.plist
  Projects/HowOldAmI/HowOldAmI.xcodeproj/project.pbxproj
Labels: bug

#465 Removed HttpRequests, ProductListMVVM and ProductListSwiftUI projects
  Projects/HttpRequests/HttpRequests.xcodeproj/project.pbxproj
  Projects/HttpRequests/HttpRequests/Info.plist
  Projects/HttpRequests/HttpRequests/Model/Album.swift
  Projects/HttpRequests/HttpRequests/Model/NetworkManager.swift
  Projects/HttpRequests/HttpRequests/Support Files/AppDelegate.swift
  Projects/HttpRequests/HttpRequests/Support Files/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/HttpRequests/HttpRequests/Support Files/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/HttpRequests/HttpRequests/Support Files/Assets.xcassets/Contents.json
  Projects/HttpRequests/HttpRequests/Support Files/Base.lproj/LaunchScreen.storyboard
  Projects/HttpRequests/HttpRequests/Support Files/Base.lproj/Main.storyboard
  Projects/HttpRequests/HttpRequests/Support Files/SceneDelegate.swift
  Projects/HttpRequests/HttpRequests/View/CollectionViewCell.swift
  Projects/HttpRequests/HttpRequests/ViewController/CollectionViewController.swift
  Projects/ProductListMVVM/ProductListMVVM.xcodeproj/project.pbxproj
  Projects/ProductListMVVM/ProductListMVVM/DetailProductModule/DetailProductViewController.swift
  Projects/ProductListMVVM/ProductListMVVM/DetailProductModule/DetailProductViewModel.swift
  Projects/ProductListMVVM/ProductListMVVM/Helpers/Box.swift
  Projects/ProductListMVVM/ProductListMVVM/Models/Product.swift
  Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductCellModule/ProductCellViewModel.swift
  Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductCellModule/ProductTableViewCell.swift
  Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductListTableViewController.swift
  Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductListViewModel.swift
  Projects/ProductListMVVM/ProductListMVVM/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/ProductListMVVM/ProductListMVVM/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/ProductListMVVM/ProductListMVVM/Resources/Assets.xcassets/Contents.json
  Projects/ProductListMVVM/ProductListMVVM/Services/DataManager.swift
  Projects/ProductListMVVM/ProductListMVVM/Services/NetworkManager.swift
  Projects/ProductListMVVM/ProductListMVVM/Storyboards/Base.lproj/LaunchScreen.storyboard
  Projects/ProductListMVVM/ProductListMVVM/Storyboards/Base.lproj/Main.storyboard
  Projects/ProductListMVVM/ProductListMVVM/Supporting Files/AppDelegate.swift
  Projects/ProductListMVVM/ProductListMVVM/Supporting Files/Info.plist
  Projects/ProductListMVVM/ProductListMVVM/Supporting Files/SceneDelegate.swift
  Projects/ProductListSwiftUI/ProductListSwiftUI.xcodeproj/project.pbxproj
  Projects/ProductListSwiftUI/ProductListSwiftUI/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/ProductListSwiftUI/ProductListSwiftUI/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/ProductListSwiftUI/ProductListSwiftUI/Assets.xcassets/Contents.json
  Projects/ProductListSwiftUI/ProductListSwiftUI/Models/Product.swift
  Projects/ProductListSwiftUI/ProductListSwiftUI/Preview Content/Preview Assets.xcassets/Contents.json
Labels: duplicate, invalid

#466 Removed RandomImages project, initialized CleanSwiftModule
  Projects/CleanSwiftModule/CleanSwiftModule.xcodeproj/project.pbxproj
  Projects/CleanSwiftModule/CleanSwiftModule/AppDelegate.swift
  Projects/CleanSwiftModule/CleanSwiftModule/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/CleanSwiftModule/CleanSwiftModule/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/CleanSwiftModule/CleanSwiftModule/Assets.xcassets/Contents.json
  Projects/CleanSwiftModule/CleanSwiftModule/Base.lproj/LaunchScreen.storyboard
  Projects/CleanSwiftModule/CleanSwiftModule/Greeting/GreetingConfigurator.swift
  Projects/CleanSwiftModule/CleanSwiftModule/Greeting/GreetingInteractor.swift
  Projects/CleanSwiftModule/CleanSwiftModule/Greeting/GreetingModels.swift
  Projects/CleanSwiftModule/CleanSwiftModule/Greeting/GreetingPresenter.swift
  Projects/CleanSwiftModule/CleanSwiftModule/Greeting/GreetingViewController.swift
  Projects/CleanSwiftModule/CleanSwiftModule/Info.plist
  Projects/CleanSwiftModule/CleanSwiftModule/Person.swift
  Projects/CleanSwiftModule/CleanSwiftModule/SceneDelegate.swift
  Projects/RandomImages/Podfile
  Projects/RandomImages/Podfile.lock
  Projects/RandomImages/RandomImages.xcodeproj/project.pbxproj
  Projects/RandomImages/RandomImages.xcworkspace/contents.xcworkspacedata
  Projects/RandomImages/RandomImages.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Projects/RandomImages/RandomImages/Extensions/ImageView+Extension.swift
  Projects/RandomImages/RandomImages/Info.plist
  Projects/RandomImages/RandomImages/Model/CacheImage.swift
  Projects/RandomImages/RandomImages/Model/NetworkAPI.swift
  Projects/RandomImages/RandomImages/Support FIles/AppDelegate.swift
  Projects/RandomImages/RandomImages/ViewController.swift
  Projects/RandomImages/RandomImages/Views/DetailViewController.swift
  Projects/RandomImages/RandomImages/Views/ImageCollectionViewCell.swift
Labels: enhancement
